# Generated by Django 3.1.5 on 2021-02-11 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counties', models.CharField(max_length=25)),
                ('codes', models.IntegerField()),
                ('cty_code', models.CharField(max_length=24)),
                ('dis', models.IntegerField(blank=True, default=0, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='IsioloKeyInstallation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sub_type', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Isiolo Key Installations',
            },
        ),
        migrations.CreateModel(
            name='IsioloProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('fname', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('couname', models.CharField(max_length=254)),
                ('scouname', models.CharField(max_length=254)),
                ('divname', models.CharField(max_length=254)),
                ('locname', models.CharField(max_length=254)),
                ('slname', models.CharField(max_length=254)),
                ('constname', models.CharField(max_length=254)),
                ('wardname', models.CharField(max_length=254)),
                ('villname', models.CharField(max_length=254)),
                ('foo', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(max_length=50)),
                ('control', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Isiolo projects',
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('locname', models.CharField(blank=True, max_length=20, null=True)),
                ('divname', models.CharField(blank=True, max_length=20, null=True)),
                ('distname', models.CharField(blank=True, max_length=20, null=True)),
                ('provname', models.CharField(blank=True, max_length=20, null=True)),
                ('code_sub', models.FloatField(blank=True, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=19, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Sub-locations',
            },
        ),
    ]
