# Generated by Django 3.1.5 on 2021-02-11 12:52

from django.db import migrations
from .. import load_counties

def load_data(apps, schema_editor):
    load_counties.run()

class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
