# Generated by Django 3.1.5 on 2021-02-11 12:57

from django.db import migrations
from .. import load_installations

def load_data(apps, schema_editor):
    load_installations.run()

class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0002_load_counties'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
