# Generated by Django 3.1.5 on 2021-02-11 12:59

from django.db import migrations
from .. import load_projects

def load_data(apps, schema_editor):
    load_projects.run()


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0003_load_installations'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
