# Generated by Django 3.1.5 on 2021-02-11 13:02

from django.db import migrations
from .. import load_sublocations


def load_data(apps, schema_editor):
    load_sublocations.run()

class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0004_load_projects'),
    ]

    operations = [
    ]
