"""
Django settings for ngeo project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

import os
import logging.config
from datetime import timedelta

from .environment import env


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def rel(*path):
    return os.path.join(BASE_DIR, *path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/{{ docs_version }}/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("NGEO_DEBUG")

ALLOWED_HOSTS = env.list("NGEO_ALLOWED_HOSTS", default=[ 
                             "192.168.60.59",
                             "127.0.0.1",
                             "0.0.0.0",])

SECRET_KEY = env.str("NGEO_SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # 3rd party apps
    "rest_framework",
    "rest_framework_tracking",
    "rest_framework_gis",
    "corsheaders",
    "django_filters",
    "workers",
    "rest_framework.authtoken",
    "leaflet",
    # our apps
    "ngeo.apps.common.apps.CommonConfig",
    "ngeo.apps.account.apps.AccountConfig",
    "ngeo.apps.mail.apps.MailConfig",
    "ngeo.apps.agents.apps.AgentsConfig",
    "ngeo.apps.projects.apps.ProjectsConfig",
    "ngeo.apps.field_officer.apps.FieldOfficerConfig",
    "ngeo.apps.shapefiles.apps.ShapefilesConfig",
    "ngeo.apps.incidence.apps.IncidenceConfig",
] + env.list("NGEO_DEV_INSTALLED_APPS", default=[])

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
] + env.list("NGEO_DEV_MIDDLEWARE", default=[])

ROOT_URLCONF = "ngeo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [rel("templates/")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "ngeo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#databases

DATABASES = {"default": env.db("NGEO_DATABASE_URL")}


# Password validation
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "account.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

SESSION_COOKIE_SECURE = env.bool("NGEO_SESSION_COOKIE_SECURE", default=True)
SESSION_COOKIE_NAME = "s"
CSRF_COOKIE_NAME = "c"


# Internationalization
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/{{ docs_version }}/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = rel("staticfiles/")
STATICFILES_DIRS = (rel("static/"),)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = rel("media/")

LOGGING_CONFIG = None
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "level": "WARNING",
        "handlers": ["console", "sentry"],
    },
    "formatters": {
        "custom": {
            "format": "%(levelname)s %(message)s (in %(module)s.%(funcName)s:%(lineno)s by %(name)s)",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "console": {"level": "DEBUG", "class": "logging.StreamHandler", "formatter": "custom"},
        "sentry": {
            "level": "WARNING",
            "class": "raven.contrib.django.raven_compat.handlers.SentryHandler",
            "tags": {"custom-tag": "x"},
        },
    },
    "loggers": {
        "apps": {"level": "DEBUG"},
        "project": {"level": "DEBUG"},
        "libs": {"level": "DEBUG"},
        "django": {"level": "INFO"},
        "gunicorn": {"level": "WARNING"},
        "workers": {"level": "DEBUG"},
    },
}
logging.config.dictConfig(LOGGING)


# ==================================================================================================
# 3RD PARTY SETTINGS
# ==================================================================================================


CORS_ORIGIN_ALLOW_ALL = True

WORKERS_SLEEP = 1
WORKERS_PURGE = 1000

REST_FRAMEWORK = {
    # "DEFAULT_RENDERER_CLASSES": (
    #     "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
    #     "rest_framework.renderers.BrowsableAPIRenderer",
    # ),
    "DEFAULT_PARSER_CLASSES": ("djangorestframework_camel_case.parser.CamelCaseJSONParser",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework.authentication.TokenAuthentication',
        # SessionAuthentication may interfere with mobile API requests. If you are experiencing ssues, try commenting out the following line.
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ),
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
        # If you're performance testing, you will want to use the browseable API
        # without forms, as the forms can generate their own queries.
        # If performance testing, enable:
        # 'example.utils.BrowsableAPIRendererWithoutForms',
        # Otherwise, to play around with the browseable API, enable:
        'rest_framework.renderers.BrowsableAPIRenderer'
    ),
}

# ==================================================================================================
# PROJECT SETTINGS
# ==================================================================================================


APP_NAME = "NGEO"
ADMIN_TITLE = "Admin"
ADMIN_HEADER = "Admin"

# Files

# MAIL
SEND_MAIL = env.bool("SEND_MAIL")
EMAIL_PROVIDER = env.str("EMAIL_PROVIDER", "smtp")  # 'smtp' or 'sendgrid'

WEB_URL = env.str("WEB_URL")
RESET_PASSWORD_URL = "{}{}".format(WEB_URL, "/reset-password/{reset_token}/{user_id}")
DEFAULT_FROM_EMAIL = "ngeo@no-reply.org"
DEFAULT_FROM_NAME = "The NGEO Team"

if EMAIL_PROVIDER == "smtp":
    EMAIL_HOST = env.str("SMTP_SERVER")
    EMAIL_HOST_USER = env.StreamHandler("SMTP_LOGIN")
    EMAIL_HOST_PASSWORD = env.str("SMTP_PASSWORD")
    EMAIL_PORT = env.str("SMTP_PORT", 587)
    EMAIL_USE_TLS = True

SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")
SENDGRID_URL = "https://api.sendgrid.com/v3/mail/send"

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("JWT",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}
