# Generated by Django 3.1.5 on 2021-02-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidence',
            new_name='Incident',
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name_plural': ' Incidents'},
        ),
    ]
