# Generated by Django 3.1.5 on 2021-02-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_officer', '0001_initial'),
        ('shapefiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('agent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapefiles.isioloproject')),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_officer.fieldofficer')),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
    ]
