# Generated by Django 3.1.5 on 2021-02-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_project',
        ),
        migrations.AddField(
            model_name='agent',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shapefiles.isioloproject'),
        ),
    ]
