# Generated by Django 3.1.5 on 2021-02-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_officer', '0002_auto_20210211_1110'),
        ('shapefiles', '0005_load_sublocations'),
        ('agents', '0002_auto_20210211_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='field_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_officer.fieldofficer'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shapefiles.isioloproject'),
        ),
    ]
