# Generated by Django 3.1.5 on 2021-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20210218_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='terms',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PERMANENT'), (2, 'TEMPORARY'), (3, 'CASUAL')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
