# Generated by Django 3.1.5 on 2021-02-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20210218_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='projects',
            new_name='isiolo_projects',
        ),
    ]
