# Generated by Django 3.1.5 on 2021-02-21 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210218_1434'),
        ('agents', '0005_auto_20210218_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='isiolo_projects',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='rating',
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='AgentReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(blank=True, null=True, verbose_name='submission date')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_report', models.FileField(blank=True, null=True, upload_to='')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='agents.agent')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Agent Returns',
            },
        ),
    ]
