# Generated by Django 3.1.5 on 2021-02-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('themes', models.CharField(choices=[('Business Incubartion', 'BUSINESS INCUBATION'), ('Agri-business', 'AGRI-BUSINESS'), ('Water & Sanitation', 'WATER-SANITATION')], default='Agri-Business', max_length=50)),
            ],
        ),
    ]
