# Generated by Django 3.1.5 on 2021-02-18 14:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20210218_1434'),
        ('field_officer', '0004_auto_20210218_1434'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='themes',
        ),
        migrations.AddField(
            model_name='project',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_officer.fieldofficer'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BUSINESS INCUBATION'), (2, 'AGRI-BUSINESS'), (3, 'WATER-SANITATION')], default=1),
        ),
    ]
