# Generated by Django 3.1.5 on 2021-02-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_officer', '0004_auto_20210218_1434'),
        ('agents', '0006_auto_20210221_1542'),
        ('projects', '0002_auto_20210218_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_officer', to='field_officer.fieldofficer'),
        ),
    ]
