# Generated by Django 3.1.5 on 2021-02-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shapefiles', '0001_initial'),
        ('field_officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofficer',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_officer', to='shapefiles.isioloproject'),
        ),
        migrations.AlterField(
            model_name='fieldofficer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
