# Generated by Django 3.1.5 on 2021-02-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_officer', '0002_auto_20210211_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='field_officer',
        ),
        migrations.AddField(
            model_name='fieldofficer',
            name='areas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_officer', to='field_officer.area'),
        ),
    ]
