# Generated by Django 3.1.5 on 2021-02-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_officer', '0003_auto_20210218_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofficer',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='fieldofficer',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='fieldofficer',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
